services:
  - type: web
    name: trivisionx-ai-frontend
    env: docker
    region: ohio
    plan: free
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://trivisionx-ai-backend.onrender.com/api"

  - type: web
    name: trivisionx-ai-backend
    env: docker
    region: ohio
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: "gemini-2.5-flash"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: "us-east-1"
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: "trivisionx_db"
      - key: SECRET_KEY
        sync: false
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: FRONTEND_URL
        value: "https://trivisionx-ai-frontend.onrender.com"
      - key: DEBUG
        value: "false"
