"""
src/agents/langgraph/state.py — Shared agent state definition
=============================================================
This TypedDict is passed through every node in the LangGraph workflow.

Agent pipeline (matches image workflow):
  Research Agent → Retrieval Agent → Citation Agent → Summary Agent → Report Agent
  (planner_node) → (retriever_node) → (citation_node) → (summarizer_node) → (report_node)
"""
from typing import TypedDict, List, Dict, Any, Annotated, Optional
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    """
    Shared state passed between all LangGraph nodes.
    All fields must have sensible defaults — nodes only update fields they own.
    """

    # ── Input ────────────────────────────────────────────────────────────────
    # The current user query
    query: str

    # Conversation ID for memory retrieval (None for stateless calls)
    conversation_id: Optional[str]

    # User ID — used for Pinecone metadata filtering (user-scoped retrieval)
    user_id: Optional[str]

    # Flag: True = full structured report, False = chat answer
    report_mode: bool

    # Answer mode: "research" = full RAG pipeline, "simple" = direct LLM (no retrieval)
    mode: str

    # ── Conversation history ─────────────────────────────────────────────────
    # Last N {role, content} turns from MongoDB — injected before graph runs
    history: List[Dict[str, str]]

    # LangChain message accumulator (add_messages reducer = append-only)
    messages: Annotated[List[BaseMessage], add_messages]

    # ── Research Agent (planner_node) ────────────────────────────────────────
    # List of targeted search queries generated by the planner
    plan: List[str]

    # ── Retrieval Agent (retriever_node) ─────────────────────────────────────
    # Raw retrieved document chunks (serialized for state transport)
    retrieved_docs: List[Dict[str, Any]]

    # ── Citation Agent (citation_node) ───────────────────────────────────────
    # Structured citation objects with doc_id, source, page, confidence, etc.
    citations: List[Dict[str, Any]]

    # ── Summary Agent (summarizer_node) ──────────────────────────────────────
    # Synthesized answer from the LLM (markdown)
    summary: str

    # ── Report Agent (report_node) ────────────────────────────────────────────
    # Final formatted markdown output (answer + references section)
    final_output: str

    # Quality metrics (coverage, confidence, completeness)
    quality_score: Dict[str, Any]

    # Flag: True = fast-path termination (e.g. for greetings to skip LLM calls)
    terminate: bool

    # ── Meta ─────────────────────────────────────────────────────────────────
    # Errors accumulated during execution (non-fatal warnings)
    errors: List[str]

    # Name of the currently executing node (streamed to frontend activity panel)
    current_node: str
