"""Markdown export utility — formats reports for download."""
from datetime import datetime


def build_markdown_report(
    query: str,
    report_text: str,
    citations: list,
    generated_at: str = None,
) -> str:
    """
    Wrap a report in a full markdown document suitable for download.
    """
    ts = generated_at or datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    header = f"""# AI Research Report

**Query:** {query}  
**Generated:** {ts}  
**Platform:** AI Research Assistant Research Copilot

---

"""
    body = report_text

    if citations:
        body += "\n\n---\n\n## Sources\n"
        for cit in citations:
            source = cit.get("filename", cit.get("source", "Unknown"))
            page = cit.get("page", "")
            page_str = f", p.{page}" if page and page != "N/A" else ""
            body += f"- {source}{page_str}\n"

    footer = "\n\n---\n*Generated by AI Research Assistant Research Copilot*\n"
    return header + body + footer
